// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKeHoI_n5aAIl8SXEJ0OixhMvNdT1_pK4',
    appId: '1:467304955222:web:6f66194fe3119f544b6af7',
    messagingSenderId: '467304955222',
    projectId: 'mindest-notes',
    authDomain: 'mindest-notes.firebaseapp.com',
    storageBucket: 'mindest-notes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK3KRmxMEuFRiX4cdMKPJDnkyV6zfQYdQ',
    appId: '1:467304955222:android:9eb255d80dcdd69e4b6af7',
    messagingSenderId: '467304955222',
    projectId: 'mindest-notes',
    storageBucket: 'mindest-notes.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9u1M9-lI2E5klnsdpEIHNwCHK7sdz58o',
    appId: '1:467304955222:ios:6742094696d01a234b6af7',
    messagingSenderId: '467304955222',
    projectId: 'mindest-notes',
    storageBucket: 'mindest-notes.firebasestorage.app',
    iosClientId: '467304955222-2rtke2hfskthha7o86oorssevbnaid58.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindsetNotes',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9u1M9-lI2E5klnsdpEIHNwCHK7sdz58o',
    appId: '1:467304955222:ios:6742094696d01a234b6af7',
    messagingSenderId: '467304955222',
    projectId: 'mindest-notes',
    storageBucket: 'mindest-notes.firebasestorage.app',
    iosClientId: '467304955222-2rtke2hfskthha7o86oorssevbnaid58.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindsetNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKeHoI_n5aAIl8SXEJ0OixhMvNdT1_pK4',
    appId: '1:467304955222:web:a222e2213393bb334b6af7',
    messagingSenderId: '467304955222',
    projectId: 'mindest-notes',
    authDomain: 'mindest-notes.firebaseapp.com',
    storageBucket: 'mindest-notes.firebasestorage.app',
  );
}
